// src/traducciones.js
export const traducciones = {
  es: {
    navHome: "Home",
    navHistoria: "Mi Historia",
    navSobreMi: "Sobre Mí",
    navDieta: "Dieta y suplementos",
    navContacto: "Contacto",
    navAsesorias: "Asesorias",
    bienvenida: "Hola, soy",
    tagline: "Gato. Influencer. Rey de tu corazón.",
    descripcion: "Bienvenido a mi mundo. Aquí comparto mi historia, mis momentos favoritos y las cosas que me hacen feliz.",
    btnSaludar: "Salúdame 🐾",
    btnFotos: "Ver mis fotos ✨",
    btnHistoria: "Conoce mi historia 📖",
    contadorSaludos: "Me has saludado {cantidad} veces hoy",
    momentos: "Mis Momentos Favoritos",
    historiaTitulo: "Mi Historia en Fotos",
    historiaP1: "Mamá de mayo: Aquí cuando Mayito llegó a mi vida, ¡me habían dicho que era hembra, le había puesto Maya, tenía llagas en la piel y no se aliviaba de un ojo! 🥺",
    historiaP2: "Mayo: Todo comenzó cuando encontré mi hogar definitivo, solia vivir bajo un arbol. Ahora, mi vida es comer, dormir y ver código y ya no visto Rosita aunque me mire hermoso en ese color, despues de 9 meses mi mamá se entero que soy macho!!",
    sobreMiTitulo: "Sobre Mí",
    sobreMiComida: "Comida favorita:",
    sobreMiComidaDetalle: "Pollito, churus y comida premium Virbac o Purina!",
    sobreMiHobby: "Hobby:",
    sobreMiHobbyDetalle: "Rasguñar lo que se me atraviese y cazar mis juguetes",
    sobreMiPoder: "Superpower:",
    sobreMiPoderDetalle: "Dormir 18 horas seguidas.",
    dietaTitulo: "Dieta y Horarios de Mayo 🍽️",
    dietaSub: "Para mantener la energía programadora al 100%, sigo una rutina estricta de alimentación premium. ****Indicada unicamente para gatos con sobrepeso****",
    thHorario: "Horario",
    thTipo: "Tipo de Alimento",
    thPorcion: "Porción",
    comida1: "Croquetas Premium (Virbac Weight loss croquetas secas)",
    comida2: "1/4 de lata Húmeda Fancy feast o purina o / (¡Hora del Churu! 🐟)",
    comida3: "Cena (Croquetas secas)",
    tiendasTitulo: "¿Dónde compran mi alimento?",
    btnMercado: "🛒 Comprar en Mercado Libre",
    btnPetsmart: "🐱 Comprar en Petsmart",
    contactoTitulo: "Contáctame",
    labelCorreo: "Correo",
    contactoPremio: "¿Quieres enviarme un premio virtual?",
    placeholderNombre: "Tu nombre",
    placeholderMensaje: "Mensaje para Mayo",
    btnForm: "Enviar Ronroneo",
    alertMiau: "🐾 ¡Miau! Mayo ha recibido tu saludo y te envía un ronroneo.",
    alertErrorNombre: "Por favor, escribe tu nombre para saber quién envía el premio.",
    alertGracias: "¡Gracias {nombre}! Mayo ha recibido tu mensaje y te envía un ronroneo. 🐾",
    suplementosTitulo: "Mis Suplementos Diarios 💊",
    thSuplemento: "Suplemento / Propósito",
    thDosis: "Dosis / Instrucción",
    supSalmon: "Aceite de Salmón (Omega 3 y 6)",
    supSalmonDosis: "1 cucharada mezclada con comida húmeda 🐟",
    supDental: "ProDen PlaqueOff (Cuidado Dental)",
    supDentalDosis: "1 cucharada espolvoreada en alimento 🦷",
    supProbioticos: "Pure Balance Pro (Probióticos / Digestión)",
    supProbioticosDosis: "1 cucharada de soporte diario 🧪",
    btnWalmart: "🛒 Comprar en Walmart",
    coachTitulo: "Especialidades🩺🐾",
    coachSub: "La Coach de Gatitos ayuda a resolver dudas de cuidado, salud preventiva y bienestar felino a través de consultas 100% personalizadas. Cada gatito es un mundo, por lo que las sesiones se adaptan por completo a la historia, edad y necesidades específicas de tu compañero felino, utilizando métodos empáticos y basados en la educación del dueño.",
    espComportamientoTitulo: "Comportamiento y Conexión Felina 🧠",
    espComportamientoDesc: "Sesiones personalizadas para aprender a conocer y entender mejor a tu gatito. Interpretación de su lenguaje corporal, maullidos y cómo reducir el estrés en casa para mejorar la convivencia diaria.",
    espNutricionTitulo: "Alimento y Nutrición 🍽️",
    espNutricionDesc: "Guía a la medida sobre qué marcas valen la pena, cómo estructurar sus porciones y el manejo de transiciones de alimento según su etapa de vida, siempre adaptándonos a tu economía o budget.",
    espVeterinarioTitulo: "Veterinarios de Confianza 🏥",
    espVeterinarioDesc: "Sugerencias y recomendaciones basadas en profesionales de la salud veterinaria totalmente probados y confiables, asegurando que tu gatito caiga en las mejores manos.",
    espAuxiliosTitulo: "Kit de Primeros Auxilios 🎒",
    espAuxiliosDesc: "Mentoría paso a paso para armar un botiquín de primeros auxilios en casa diseñado para las necesidades de tu hogar, y capacitación sobre cómo reaccionar oportunamente ante incidentes comunes.",
    coachModalidad: "💡 Consultas a tu medida: Sesiones personalizadas que se pueden llevar a cabo de forma remota (llamada o videollamada) para tu mayor comodidad.",
    priceInfo : "$300 MXN sesión (transferencia por adelantado en nuevos clientes)",
    btnAgenda: "📅 Agendar Asesoría / Contactar Coach",
    moodTitulo: "👑 Mood actual",
    moodDesc: "Siesta Profesional",
    seguidores: "60,000mil seguidores",
    agradecimiento: "Gracias por tanto amor 💙",
    reciboTalla: "Talla",
    navGatos: "Galería de Gatos"
  },
  en: {
    navHome: "Home",
    navHistoria: "My Story",
    navSobreMi: "About Me",
    navDieta: "Diet & Supplements",
    navContacto: "Contact",
    bienvenida: "Hi, I am",
    tagline: "Cat. Influencer. King of your heart.",
    descripcion: "Welcome to my world. Here I share my story, my favorite moments, and the things that make me happy.",
    btnSaludar: "Greet me 🐾",
    btnFotos: "See my photos ✨",
    btnHistoria: "Meet my history 📖",
    contadorSaludos: "You have greeted me {cantidad} times today",
    momentos: "My Favorite Moments",
    historiaTitulo: "My Story in Photos",
    historiaP1: "Mayo's mom: Here is when Mayito came into my life, they told me he was a female, I named him Maya, he had skin sores and his eye wouldn't heal! 🥺",
    historiaP2: "Mayo: It all started when I found my forever home, before I used to live underneath a tree. Now, my life is eating, sleeping, and looking at code, and I no longer wear pink even though I look gorgeous in that color, after 9 months my mom found out I am a male!!",
    sobreMiTitulo: "About Me",
    sobreMiComida: "Favorite food:",
    sobreMiComidaDetalle: "Chicken, churus, and premium Virbac or Purina food!",
    sobreMiHobby: "Hobby:",
    sobreMiHobbyDetalle: "Scratching whatever gets in my way and hunting my toys",
    sobreMiPoder: "Superpower:",
    sobreMiPoderDetalle: "Sleeping for 18 hours straight.",
    dietaTitulo: "Mayo's Diet and Schedule 🍽️",
    navAsesorias: "Coaching",
    dietaSub: "To keep my programmer energy at 100%, I follow a strict premium feeding routine. ****Indicated only for overweight cats****",
    thHorario: "Schedule",
    thTipo: "Food Type",
    thPorcion: "Portion",
    comida1: "Premium Kibble (Virbac Weight loss dry kibble)",
    comida2: "1/4 Can of Wet Food Fancy feast or purina or / (Churu Time! 🐟)",
    comida3: "Dinner (Dry kibble)",
    tiendasTitulo: "Where do they buy my food?",
    btnMercado: "🛒 Buy on Mercado Libre",
    btnPetsmart: "🐱 Buy on Petsmart",
    contactoTitulo: "Contact Me",
    labelCorreo: "Email",
    contactoPremio: "Do you want to send me a virtual treat?",
    placeholderNombre: "Your name",
    placeholderMensaje: "Message for Mayo",
    btnForm: "Send Purr",
    alertMiau: "🐾 Meow! Mayo received your greeting and sends you a purr.",
    alertErrorNombre: "Please write your name to know who is sending the treat.",
    alertGracias: "Thank you {nombre}! Mayo has received your message and sends you a purr. 🐾",
    suplementosTitulo: "My Daily Supplements 💊",
    thSuplemento: "Supplement / Purpose",
    thDosis: "Dosage / Instruction",
    supSalmon: "Salmon Oil (Omega 3 & 6)",
    supSalmonDosis: "1 tablespoon mixed with wet food 🐟",
    supDental: "ProDen PlaqueOff (Dental Care)",
    supDentalDosis: "1 tablespoon sprinkled on food 🦷",
    supProbioticos: "Pure Balance Pro (Probiotics / Digestion)",
    supProbioticosDosis: "1 tablespoon daily support 🧪",
    btnWalmart: "🛒 Buy on Walmart",
    coachTitulo: "Specialties🩺🐾",
    coachSub: "The Cat Coach helps resolve care, preventive health, and feline well-being questions through 100% personalized consultations. Every kitty is a different world, so sessions completely adapt to the history, age, and specific needs of your feline companion, using empathetic methods based on owner education.",
    espComportamientoTitulo: "Feline Behavior & Connection 🧠",
    espComportamientoDesc: "Personalized sessions to learn to know and understand your kitty better. Interpretation of their body language, meows, and how to reduce stress at home to improve daily coexistence.",
    espNutricionTitulo: "Food & Nutrition 🍽️",
    espNutricionDesc: "Tailored guidance on which brands are worth it, how to structure portions, and managing food transitions according to their life stage, always adapting to your economy or budget.",
    espVeterinarioTitulo: "Trusted Veterinarians 🏥",
    espVeterinarioDesc: "Suggestions and recommendations based on fully tested and trusted veterinary health professionals, ensuring your kitty falls into the best hands.",
    espAuxiliosTitulo: "First-Aid Kit 🎒",
    espAuxiliosDesc: "Step-by-step mentorship to assemble a home first-aid kit designed for your household's needs, and training on how to react opportunely to common incidents.",
    coachModalidad: "💡 Tailored consultations: Personalized sessions that can be carried out remotely (phone or video call) for your convenience.",
    priceInfo: "$300 MXN MXN per session (advance transfer for new clients)",
    btnAgenda: "📅 Schedule Session / Contact Coach",
    moodTitulo: "👑 Current Mood",
    moodDesc: "Professional Nap",
    seguidores: "60k followers",
    agradecimiento: "Thanks for so much love 💙",
    reciboTalla: "Size",
    navGatos: "Cat Gallery"
  }
};